/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Log in user */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["LoginRequest"];
        };
      };
      responses: {
        /** @description Successfully logged in */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthToken"];
          };
        };
        default: components["responses"]["GeneralError"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh JWT token */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Token refreshed successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthToken"];
          };
        };
        default: components["responses"]["GeneralError"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a new user */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["RegisterRequest"];
        };
      };
      responses: {
        /** @description User registered successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthToken"];
          };
        };
        default: components["responses"]["GeneralError"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ping": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ping the server
     * @description Check if the server is running
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Server is running */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example pong */
              message?: string;
            };
          };
        };
        default: components["responses"]["GeneralError"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/posts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Posts */
    get: {
      parameters: {
        query?: {
          /** @description Number of items to skip before starting to collect the result set */
          offset?: number;
          /** @description Maximum number of items to return */
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Paginated list of Posts */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PaginatedPosts"];
          };
        };
      };
    };
    put?: never;
    /** Create a new Post */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreatePostRequest"];
        };
      };
      responses: {
        /** @description Post saved successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Post"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/posts/{postId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Post by ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID of the Post to retrieve */
          postId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Post retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Post"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete Post */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID of the Post to delete */
          postId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Post deleted successfully */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    /** Update Post */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID of the Post to update */
          postId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdatePostRequest"];
        };
      };
      responses: {
        /** @description Post updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Post"];
          };
        };
      };
    };
    trace?: never;
  };
  "/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current user
     * @description Retrieve the currently authenticated user's profile
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Current user profile */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        401: components["responses"]["GeneralError"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AuthToken: {
      accessToken?: string;
      refreshToken?: string;
    };
    CreatePostRequest: {
      authorId: string;
      content: string;
      title: string;
    };
    GeneralError: {
      /** @description Validation errors for specific fields */
      fieldErrors?: {
        [key: string]: string;
      };
      /** @description A description of the error */
      message: string;
    };
    LoginRequest: {
      email: string;
      /** Format: password */
      password: string;
    };
    PaginatedPosts: {
      items: components["schemas"]["Post"][];
      /** @description Limit of items per page */
      limit?: number;
      /** @description Offset of the current page */
      offset?: number;
      /** @description Total number of posts matching the query */
      total: number;
    };
    RegisterRequest: {
      email: string;
      password: string;
    };
    UpdatePostRequest: {
      content?: string;
      title?: string;
    };
    User: {
      id: string;
      email: string;
    };
    Post: {
      id: string;
      authorId: string;
      content: string;
      title: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
  };
  responses: {
    /** @description A general error response */
    GeneralError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["GeneralError"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
